openssl
readline
libyaml

sl
git
zsh
tmux
direnv
z
ctags
ack
hub
pwgen
fontforge
wget
tree
tig
terminal-notifier
cheat
peco

reattach-to-user-namespace
https://raw.github.com/Homebrew/homebrew-dupes/master/grep.rb

