openssl
readline
libyaml

sl
git
zsh
tmux
direnv
z
ctags
ack
hub
pwgen
fontforge
wget
tree
tig
terminal-notifier
cheat
peco
ghc
cabal-install
redis
node

rbenv
ruby-build

reattach-to-user-namespace
https://raw.github.com/Homebrew/homebrew-dupes/master/grep.rb

