openssl
readline
libyaml

gnupg

sl
git
zsh
tmux
direnv
z
ctags
hub
pwgen
fontforge
wget
tree
tig
terminal-notifier
cheat
peco
ghc
cabal-install
redis
node
gnu-sed
unzip
maven

rbenv
ruby-build

reattach-to-user-namespace
grep

python

lua
vim
