[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = "has('nvim')"

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'tyru/caw.vim'

# ColorSchemeを上書きする
# .vim/after/colorsに同名ファイルを置くと上書きされる
[[plugins]]
repo = 'vim-scripts/AfterColors.vim'

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = 'javascript'
hook_add = 'let g:jsx_ext_required = 0'

[[plugins]]
repo = 'vim-scripts/closetag.vim'
on_ft = ['html', 'xml']
hook_add = 'let g:closetag_html_style=1'

[[plugins]]
repo = 'fatih/vim-go'
